### ISSUE TITLE
Setting memory events with  VMI_MEMACCESS_N causes the VM to pause indefinetly

### ISSUE THREAD

**Issue by igor-benevides** [KVM-VMI/libvmi#29]
I was trying to understand how the `vmi_clear_event() `function works and noticed in case of an especific event it sets the page permission to VMI_MEMACCESS_N. Apparently this enforces the original page permissions (i'm really not sure if this is truly the case or it enforces the current permissions), but anyway i though this could apply to generic events, so looking at:
`status_t 
vmi_set_mem_event(vmi_instance_t vmi, addr_t gfn, vmi_mem_access_t access, uint16_t slat_id)
{`

It makes a check if the permission is VMI_MEMACCESS_N:
`if ( VMI_MEMACCESS_N != access ) {`
Inside this condition it seeks for a generic event with the same permissions, so i though maybe that permission is supposed to be used to remove specific pages from a generic event, but when i set any memory event through `vmi_set_mem_event` or even a specific event with `SETUP_MEM_EVENT` macro with `VMI_MEMACCESS_N` the guest stops indefinetly

Here's how i thought i could remove a specific page from a generic event upon callback
```
event_response_t mm_callback(vmi_instance_t vmi, vmi_event_t *event)
{
    printf("called\n");
    printf("removing event\n");
    vmi_set_mem_event(vmi, event->mem_event.gfn, VMI_MEMACCESS_N, 0);
    printf("removed event\n");
    return 0;
}
```

The event is setted normally but the guest is paused forever, even with `vmi_resume_vm()` it doesn't respond

This is the debug log when the callback is called:

**--Received pagefault event
called
removing event
--Done setting memaccess on GPFN: 0xa60e6
removed event**

**Comment by Wenzel** [comment]
Hi @igor-benevides,

I made a mistake while implementing `VMI_MEMACCESS_N` page access for the KVM driver.
This was fixed just a few hours ago:
https://github.com/libvmi/libvmi/pull/844/commits/e033cb09f6a0f22c0962d77568285250e96d5f0b

Indeed, `VMI_MEMACCESS_N` is suppose to give back all EPT permissions to the page.

Please pull from the `kvmi` branch, and see if this solves your problem.

**Comment by igor-benevides** [comment]
It works! I forgot to update the repository before opening the issue sorry, thank you.
