### ISSUE TITLE
KVM-v7 error in vagrant provisioning

### ISSUE THREAD

**Issue by aghamir** [KVM-VMI/libvmi#37]
Hi @Wenzel ,
libvmi got error during build with bellow strerr:
`/vagrant/libvmi/libvmi/driver/kvm/kvm.c: In function ‘init_kvmi’:\n/vagrant/libvmi/libvmi/driver/kvm/kvm.c:383:12: error: variable ‘features’ has initializer but incomplete type\n     struct kvmi_features features = {0};`

Do I suppose to to checkout to specific commit which determined in `kvm-vmi` repository? Because I think all of the submodules are on `kvmi-v7` branch now.

Thanks a lot.

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by mtarral** [comment]
Hi @aghamir,

Thanks for your report, I found the issue:
https://github.com/KVM-VMI/kvm-vmi/blob/kvmi-v7/vagrant/ansible/roles/kvm/tasks/libkvmi.yml

`libkvmi` is still checked out using its `kvmi-v6` branch.
This should be `master`.

As you workaround, you can edit the `libkvmi.yml` task, and replace the branch, and rebuild the vagrant.

I will push a fix tonight.

Thanks !

**Comment by aghamir** [comment]
I love you Mathieu. You are awesome. I'll fix that.
P.S.: How this happens to github(38 response :) )?

**Comment by mtarral** [comment]
Hey, i'm so sorry for the insane spamming, my browser had an issue where the comment was posted, but I had no feedback, leading me to click 38 times like a monkey :clown:

Always happy to help !

**Comment by Wenzel** [comment]
commit https://github.com/KVM-VMI/kvm-vmi/commit/ee3587e12190a8c783d976f30f522a7c14f9aeef fixed this issue.

@aghamir feel free to close
