### ISSUE TITLE
Add vmi_flags_sanity_check for KVM driver

### ISSUE THREAD

**Issue by Wenzel** [KVM-VMI/libvmi#38]
The KVM driver doesn't check whether the `vmi_mem_access_t` are valid.
There are invalid EPT configurations, such as:
![Capture d’écran de 2020-11-05 16-31-30](https://user-images.githubusercontent.com/964610/98351792-77253680-201d-11eb-9d1b-74caa22d85a7.png)

A function are exists in the Xen driver:
https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events_private.h#L157

@tklengyel , should make it available to all drivers ? Or should I copy paste this in the KVM driver.
since it's x86 specific I'm not sure how you would like to handle that behavior.

Thanks

**Comment by tklengyel** [comment]
Either is fine by me
